apiVersion: v1
kind: Service
metadata:
  name: house-price-ml-service
spec:
  selector:
    app: house-price-ml
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 8080  # container port
  type: LoadBalancer    # Use NodePort if you’re running Minikube
