apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-model-deployment
  labels:
    app: house-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-model
  template:
    metadata:
      labels:
        app: house-model
    spec:
      containers:
        - name: house-model
          # 👇 Replace this image with your Docker Hub image name
          image: <your-dockerhub-username>/house-model:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
            - name: MODEL_PATH
              value: "model.joblib"
