apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-ml
  labels:
    app: house-price-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price-ml
  template:
    metadata:
      labels:
        app: house-price-ml
    spec:
      containers:
        - name: house-price-ml
          image: ghcr.io/koushiki2009-sudo/house-price-mlops:latest   # ✅ Your GHCR image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
            - name: MODEL_PATH
              value: "/app/model.joblib"
      # ✅ Include this if GHCR is private
      imagePullSecrets:
        - name: regcred-ghcr
